### ISSUE TITLE
elgg etherpad "add a pad" not working

### ISSUE THREAD

**Issue by sachinbanugariya** [nlybe/Elgg-Etherpad#5]
hello,

version info:
elgg 2.0
etherpad_lite v1.6.1
nginx 1.8.1
PHP 5.6.29

we installed etherpad_lite latest_version, on our xxx server,
that is working fine and we are able to add pad using http://localhost:9001.

and we also installed elgg_ethernet plugin on same xxx server,
settings is also filled with our localhost servername and that api_key.

we using nginx, so on nginx.conf i also add below block for ethernet:
 location /pad {
                rewrite                /pad/(.*) /$1 break;
                rewrite                ^/pad$ /pad/ permanent;
                proxy_pass             http://localhost:9001/;
                proxy_redirect         / /pad/;
                proxy_set_header       Host $host;
                proxy_buffering off;
}

now the issue we are able to create/add pad using default http://localhost:9001,
but using elgg_ethernet plugin, after installation and configured settings, i am able to see add pad button, using that button if i try to add pad, then not able to add pad, and getting issue like: "error while save page".
when i click on "add pad" then my site redirect on https://localhost/etherpad/add/38.

so please check below backend error and let us know how and where i can debug and solve i\this issue.

2017/01/23 23:27:35 [error] 32723#0: *21 FastCGI sent in stderr: "PHP message: exception 'UnexpectedValueException' with message 'JSON response could not be decoded' in /usr/local/nginx/html/elgg/mod/etherpad/vendors/etherpad-lite-client.php:75
Stack trace:
#0 /usr/local/nginx/html/elgg/mod/etherpad/vendors/etherpad-lite-client.php(34): EtherpadLiteClient->call('createGroupIfNo...', Array, 'POST')
#1 /usr/local/nginx/html/elgg/mod/etherpad/vendors/etherpad-lite-client.php(118): EtherpadLiteClient->post('createGroupIfNo...', Array)
#2 /usr/local/nginx/html/elgg/mod/etherpad/classes/ElggPad.php(101): EtherpadLiteClient->createGroupIfNotExistsFor('38@docket.cente...')
#3 /usr/local/nginx/html/elgg/mod/etherpad/classes/ElggPad.php(30): ElggPad->startSession()
#4 /usr/local/nginx/html/elgg/mod/etherpad/actions/etherpad/save.php(116): ElggPad->save()
#5 /usr/local/nginx/html/elgg/engine/classes/Elgg/ActionsService.php(131): include('/usr/local/ngin...')
#6 /usr/local/nginx/html/d" while reading response header from upstream, client: , server: localhost, request: "POST /action/etherpad/save HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "https://localhost/etherpad/add/38"

thanks.

**Comment by nlybe** [comment]
You will have to check and debug the file /usr/local/nginx/html/elgg/mod/etherpad/vendors/etherpad-lite-client.php, on line 7 before. 
Check one by one the values or variable before that line to understand what is wrong
